routes/web.php
<?php
use App\Http\Controllers\AspirasiController;
use App\Http\Controllers\AbsensiController;
use App\Http\Controllers\AcaraController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\DashboardUserController;
use App\Http\Controllers\DashboardAdminController;
use App\Http\Controllers\ListUserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

//initial admin
Route::group(['middleware' => ['role']], function() {
    Route::resource('admins', DashboardAdminController::class);
    Route::resource('list', ListUserController::class);
});
// Route::resource('admins', DashboardAdminController::class);
Route::resource('aspirasi', AspirasiController::class);
Route::resource('absensi', AbsensiController::class);
Route::resource('list', ListUserController::class);
Route::get('/export-users',[ListUserController::class,'exportUsers'])->name('export-users');
Route::get('/acara/cetak_pdf',[DashboardUserController::class,'cetak_pdf'])->name('export-acara');



//initial users
Route::resource('user', DashboardUserController::class);
Route::get('/aspirasi/create',[AspirasiController::class,'create_aspirasi']);
Route::get('/users/profile',[ProfileController::class,'index']);
//kirim data db

//Acara
Route::resource('acara', AcaraController::class);

Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/', [App\Http\Controllers\HomeController::class, 'adminHome'])->name('home')->middleware('role');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function profile()
    {
        return $this->hasOne(Profile::class);
    }

    public function aspirasi()
    {
        return $this->hasMany(Aspirasi::class);
    }
}

resources/views/users/dashboard/acara_pdf.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>List Acara</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
	<style type="text/css">
		table tr td,
		table tr th{
			font-size: 9pt;
		}
	</style>
	<center>
		<h5>Liast Acara </h4>
	</center>
 
	<table class='table table-bordered'>
		<thead>
			<tr>
				<th>No</th>
				<th>Nama Acara</th>
				<th>Tanggal</th>
				<th>Tanggal Acara</th>
			</tr>
		</thead>
		<tbody>
			@php $i=1 @endphp
			@foreach($acr as $acara)
			<tr>
				<td>{{ $i++ }}</td>
				<td>{{$acara->name}}</td>
				<td>{{$acara->date}}</td>
				<td>{{$acara->desc}}</td>
			</tr>
			@endforeach
		</tbody>
	</table>
 
</body>
</html>

resources/views/users/dashboard/dashboard.blade.php
@extends('layouts.master_users')

@section('title')
Dashboard
@endsection

@section('content2')
Daftar Acara
@endsection

@section('btnDownload')
<a class="btn btn-primary btn-sm" style="max-height: 40px" href="{{ route('export-acara') }}">Export List Acara to PDF</a>
@endsection

@section('content')
<div class="card-group">
   @foreach ($acr as $acrus)    
   <div class="col-lg-4 p-0">
      <div class="card mb-3 mr-3">
        <img class="card-img-top" src="{{ asset('storage/acara_images/'.$acrus->image) }}" style="width: 100%" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">{{ Str::Limit($acrus->name, 15) }}</h5>
          <p class="card-text">{{ Str::limit($acrus->desc, 100) }}</p>
        </div>
        <a class="btn btn-primary rounded block" href="{{ route('user.show', $acrus->id) }}">Detail Acara</a>
        <div class="card-footer">
          <small class="text-muted">{{ $acrus->date }}</small>
        </div>
      </div>
   </div>
   @endforeach
   {{ $acr->links() }}  
</div>
@endsection

resources/views/users/dashboard/detail_user.blade.php
@extends('layouts.master_users')

@section('title')
Dashboard
@endsection

@section('content2')
Detail Acara
@endsection

@section('content')
<div class="card-deck">
   <div class="card">
      <img class="card-img-top" src="{{ asset('storage/acara_images/'. $acr->image) }}" style="width: 100%" alt="Card image cap">
      <div class="card-body">
         <h5 class="card-title">{{ $acr->name }}</h5>
         <p class="card-text">{{ $acr->desc }}</p>
         <div class="d-flex justify-content-between">
            <p class="card-text"><small class="text-muted">{{ $acr->date }}</small></p>
            <a class="btn btn-secondary rounded" href="{{ route('user.index') }}">Back</a>
         </div>
      </div>
   </div>
</div>

@endsection