routes/web.php
<?php
use App\Http\Controllers\AspirasiController;
use App\Http\Controllers\AbsensiController;
use App\Http\Controllers\AcaraController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\DashboardUserController;
use App\Http\Controllers\DashboardAdminController;
use App\Http\Controllers\ListUserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

//initial admin
Route::group(['middleware' => ['role']], function() {
    Route::resource('admins', DashboardAdminController::class);
    Route::resource('list', ListUserController::class);
});
// Route::resource('admins', DashboardAdminController::class);
Route::resource('aspirasi', AspirasiController::class);
Route::resource('absensi', AbsensiController::class);
Route::resource('list', ListUserController::class);
Route::get('/export-users',[ListUserController::class,'exportUsers'])->name('export-users');
Route::get('/acara/cetak_pdf',[DashboardUserController::class,'cetak_pdf'])->name('export-acara');



//initial users
Route::resource('user', DashboardUserController::class);
Route::get('/aspirasi/create',[AspirasiController::class,'create_aspirasi']);
Route::get('/users/profile',[ProfileController::class,'index']);
//kirim data db

//Acara
Route::resource('acara', AcaraController::class);

Auth::routes();

//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/', [App\Http\Controllers\HomeController::class, 'adminHome'])->name('home')->middleware('role');

app/Models/Absensi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Absensi extends Model
{
    use HasFactory;
    protected $table = "absensi";
    protected $fillable = [
        "acara_id", 
        "user_id",
        "keterangan"
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function profile()
    {
        return $this->hasOne(Profile::class);
    }

    public function aspirasi()
    {
        return $this->hasMany(Aspirasi::class);
    }
}

app/Http/Controllers/AbsensiController.php
<?php

namespace App\Http\Controllers;

use App\Models\Absensi;
use App\Models\Acara;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class AbsensiController extends Controller
{

    public function __construct()
    {
        $this->middleware('role')->except('store' , 'create');
    }
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $absensi = Absensi::all();
        //dd($cast);
        
        return view('admin.absensi.index', compact('absensi'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $acara = Acara::all();
        return view('users.absensi.tambah', compact('acara'));
    }

   /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'acara_id' => 'required',
            'keterangan' => 'required'
        ]);
        $absensi = new Absensi();

        $absensi->acara_id = $request->input('acara_id');
        $absensi->user_id = auth()->user()->id;
        $absensi->keterangan = $request->input('keterangan');
        $absensi->save();
        return redirect()->route('user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Absensi
     * @return \Illuminate\Http\Response
     */
    public function show($id){
        $absensi = Absensi::find($id);
        $users = User::find($absensi->user_id);
        $acara = Acara::find($absensi->acara_id);
        return view('admin.absensi.detail',compact('absensi', 'users', 'acara'));
    }

   /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Absensi
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $absensi = Absensi::find($id);
        return view('admin.absensi.edit', compact('absensi'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Absensi
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id){
        $request->validate([
            'acara_id'=> 'required',
            'keterangan'=> 'required'
        ]);

        $absensi = Absensi::find($id);
        
        $absensi->acara_id = $request->input('acara_id');
        $absensi->user_id = auth()->user()->id;
        $absensi->keterangan = $request->input('keterangan');
        $absensi->save();
        return redirect('/absensi');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Absensi
     * @return \Illuminate\Http\Response
     */
    public function destroy( $id)
    {
        Absensi::find($id)->delete();
        return redirect('/absensi');
    }
}

resources/views/users/absensi/index.blade.php
@extends('layouts.master_user')

@section('title')
Acara
@endsection

@section('content')
{{-- Header Content --}}
<div class="row">
  <div class="col-lg-4 col-md-12 col-6 mb-4">
    <div class="card card-gradient" style="max-height: 150px">
      <div class="card-body">
        <div class="card-title d-flex align-items-start justify-content-between">
          <div class="d-flex">
            <div class="me-2">
              <span class="badge bg-label-info p-2"><i class="bx bxs-calendar-event text-info"></i></span>
            </div>
          </div>
          <div class="dropdown">
            <button class="btn p-0" type="button" id="cardOpt3" data-bs-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">
              <i class="bx bx-dots-vertical-rounded"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="cardOpt3">
              <a class="dropdown-item" href="javascript:void(0);">View More</a>
              <a class="dropdown-item" href="javascript:void(0);">Delete</a>
            </div>
          </div>
        </div>
        <span class="fw-semibold d-block mb-1">Acara Soon</span>
        <h3 class="card-title mb-2">4</h3>
      </div>
    </div>
  </div>
  <div class="col-lg-4 col-md-12 col-6 mb-4">
    <div class="card card-gradient" style="max-height: 150px">
      <div class="card-body">
        <div class="card-title d-flex align-items-start justify-content-between">
          <div class="d-flex">
            <div class="me-2">
              <span class="badge bg-label-success p-2"><i class="bx bx-calendar-check text-success"></i></span>
            </div>
          </div>
          <div class="dropdown">
            <button class="btn p-0" type="button" id="cardOpt3" data-bs-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">
              <i class="bx bx-dots-vertical-rounded"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="cardOpt3">
              <a class="dropdown-item" href="javascript:void(0);">View More</a>
              <a class="dropdown-item" href="javascript:void(0);">Delete</a>
            </div>
          </div>
        </div>
        <span class="fw-semibold d-block mb-1">Acara Done</span>
        <h3 class="card-title mb-2">3</h3>
      </div>
    </div>
  </div>
  <div class="col-lg-4 col-md-12 col-6 mb-4">
    <div class="card card-gradient" style="max-height: 150px">
      <div class="card-body">
        <div class="card-title d-flex align-items-start justify-content-between">
          <div class="d-flex">
            <div class="me-2">
              <span class="badge bg-label-info p-2"><i class="bx bx-group text-info"></i></span>
            </div>
          </div>
          <div class="dropdown">
            <button class="btn p-0" type="button" id="cardOpt3" data-bs-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">
              <i class="bx bx-dots-vertical-rounded"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="cardOpt3">
              <a class="dropdown-item" href="javascript:void(0);">View More</a>
              <a class="dropdown-item" href="javascript:void(0);">Delete</a>
            </div>
          </div>
        </div>
        <span class="fw-semibold d-block mb-1">Total User</span>
        <h3 class="card-title mb-2">100</h3>
      </div>
    </div>
  </div>
</div>
{{-- End Header Content --}}

{{-- Button Modal Create --}}
<button type="button" class="btn btn-primary mb-3" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
  <span class="tf-icons bx bxs-plus-square"></span>&nbsp; Tambahkan Acara
</button>
{{-- Button Modal Create --}}

{{-- Modal Create --}}
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
  aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Form Create Acara</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="post" action="{{ route('acara.store')}}" id="myForm" enctype="multipart/form-data">
          @csrf
          <div class="mb-3">
            <label class="form-label" for="basic-icon-default-image">Image</label>
            <div class="input-group input-group-merge">
              <span id="basic-icon-default-image2" class="input-group-text"><i class="bx bxs-image-add"></i></span>
              <input type="file" class="form-control" name="image" id="basic-icon-default-image" aria-label="John Doe"
                aria-describedby="basic-icon-default-image2" />
            </div>
          </div>
          <div class="mb-3">
            <label class="form-label" for="basic-icon-default-name">Title Acara</label>
            <div class="input-group input-group-merge">
              <span id="basic-icon-default-name2" class="input-group-text"><i class="bx bxs-pencil"></i></span>
              <input type="text" id="basic-icon-default-name" name="name" class="form-control" placeholder="Diesnatalis"
                aria-label="ACME Inc." aria-describedby="basic-icon-default-name2" />
            </div>
          </div>
          <div class="mb-3">
            <label class="form-label" for="basic-icon-default-tanggal">Tanggal</label>
            <div class="input-group input-group-merge">
              <span class="input-group-text"><i class="bx bx-calendar"></i></span>
              <input type="date" id="basic-icon-default-tanggal" name="date" class="form-control" aria-label="john.doe"
                aria-describedby="basic-icon-default-tanggal2" />
            </div>
          </div>
          <div class="mb-3">
            <label class="form-label" for="basic-icon-default-deskripsi">Deskripsi</label>
            <div class="input-group input-group-merge">
              <span id="basic-icon-default-deskripsi2" class="input-group-text"><i class="bx bx-notepad"></i></span>
              <textarea id="basic-icon-default-deskripsi" class="form-control" placeholder="Deskripsi" name="desc"
                aria-describedby="basic-icon-default-deskripsi2"></textarea>
            </div>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Send</button>
      </div>
      </form>
    </div>
  </div>
</div>
{{-- End Modal Create --}}

{{-- card index --}}
<div class="row">
  @foreach ($acr as $acara )
  <div class="col-md-6">
    <div class="card mb-3">
      <div class="row g-0">
        <div class="col-md-4">
          <img class="card-img card-img-left" src="{{ asset('storage/acara_images/'.$acara->image) }}"
            style="height: 100%;" alt="Card image" />
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <div class="d-flex justify-content-between">
              <h5 class="card-title">{{ $acara->name }}</h5>
              <div class="dropdown">
                <button class="btn p-0" type="button" id="cardOpt3" data-bs-toggle="dropdown" aria-haspopup="true"
                  aria-expanded="false">
                  <i class="bx bx-dots-vertical-rounded"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="cardOpt3">
                  <a class="dropdown-item gradient-edit rounded" href="{{ route('acara.edit', $acara->id) }}">Edit</a>
                  <a class="dropdown-item gradient-detail rounded" href="{{ route('acara.show', $acara->id) }}">Detail</a>
                  <a class="dropdown-item gradient-delete rounded" href="{{ route('acara.destroy', $acara->id) }}">Delete</a>
                </div>
              </div>
            </div>
            <p class="card-text">
              {{ Str::limit($acara->desc, 30) }}
            </p>
            <p class="card-text"><small class="text-muted">{{ $acara->date }}</small></p>
          </div>
        </div>
      </div>
    </div>
  </div>
  @endforeach
</div>
{{-- end card index --}}
@endsection

resources/views/users/absensi/tambah.blade.php
@extends('layouts.master_users')
@section('title')
Tambah Absensi
@endsection

@section('content2')
Form Tambah Absensi
@endsection

@section('content')

<div class="row">
  <div class="col-lg-12 mb-4 order-0">
     <div class="card ">
        <div class="d-flex align-items-end row">
           <div class="col-sm-12">
              <div class="card-body rounded shadow">
                 <h5 class="card-title text-primary">List Acara</h5>
                 <table class="table datatables" id="dataTable-1">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col">Nama Acara</th>
                        <th scope="col">Acara Id</th>
                      </tr>
                    </thead>
                    <tbody>
                       @forelse ($acara as $key => $value)
                       <tr>
                           <td>{{$key + 1}}</td>
                           <td>{{$value->name}}</td>
                           <td>{{$value->id}}</td>
                       </tr>
                   @empty
                       <tr>
                           <td>Tidak Ada Data</td>
                       </tr>
                   @endforelse
                   </tbody>
                  </table>
              </div>
           </div>
           
        </div>
     </div>
  </div>
</div>

<form action="/absensi" method="POST">
  @csrf
    <div class="mb-3">
      <label class="form-label">Acara (id)</label>
      <input type="number" class="form-control rounded" name="acara_id" >
    </div>
    @error('acara_id')
    <div class="alert alert-danger">{{ $message }}</div>
@enderror

    <div class="mb-3">
      <label class="form-label">Keterangan</label>
      <input type="text" class="form-control rounded" name="keterangan" >
    </div>
    @error('keterangan')
    <div class="alert alert-danger">{{ $message }}</div>
@enderror
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
@endsection